export default [
  "",
  {
    title: "Java热门面试题",
    collapsable: true,
    children: [
      "Java热门面试题/JDK和JRE有什么区别？.md",
      "Java热门面试题/Java的重要特点说几个.md",
      "Java热门面试题/==和equals的区别是什么？.md",
      "Java热门面试题/BIO、NIO、AIO有什么区别？.md",
      "Java热门面试题/final在Java中有什么引用？.md",
      "Java热门面试题/Java的基本数据类型有哪些？.md",
      "Java热门面试题/Math.round、Math.ceil、Math.floor用法.md",
      "Java热门面试题/String,StringBuffer,StringBuilder之间的区别和联系.md",
      "Java热门面试题/String两种创建对象的区别.md",
      "Java热门面试题/为什么要使用克隆 怎么实现对象克隆 克隆有几种方式和它们的区别？.md",
      "Java热门面试题/什么是反射？反射有哪些作用？反射在Spring中的体现.md",
      "Java热门面试题/常见的运行时异常有哪些？.md",
      "Java热门面试题/抽象类和普通类的区别在哪里？.md",
      "Java热门面试题/接口和抽象类有什么区别和联系？.md",
      "Java热门面试题/重写和重载的区别和使用场景.md",
      "Java热门面试题/HashMap和HashTable有什么区别？.md",
      "Java热门面试题/HashMap的实现原理.md",
      "Java热门面试题/什么是双亲委派模型？.md",
      "Java热门面试题/实例化对象有哪几种方式？.md",
      "Java热门面试题/类什么时候会被加载？.md",
    ],
  },
  {
    title: "计算机网络热门面试题",
    collapsable: true,
    children: [
      "计算机网络热门面试题/GET 请求和 POST 请求的区别.md",
      "计算机网络热门面试题/http和https的区别.md",
      "计算机网络热门面试题/OSI七层协议？.md",
      "计算机网络热门面试题/TCP三次握手和四次挥手，为什么不能是两次握手，三次挥手？.md",
      "计算机网络热门面试题/TCP和UDP传输协议的区别？.md",
      "计算机网络热门面试题/TCP和UDP的区别.md",
      "计算机网络热门面试题/TLS加密的过程.md",
      "计算机网络热门面试题/TLS的握手过程.md",
      "计算机网络热门面试题/对加密方式有了解吗？.md",
      "计算机网络热门面试题/拥塞控制、超时重传的具体原理？.md",
    ],
  },
  {
    title: "数据库热门面试题",
    collapsable: true,
    children: [
      "数据库热门面试题/MySQL回表.md",
      "数据库热门面试题/MySQL常见索引.md",
      "数据库热门面试题/MySQL的undolog,redolog,binlog.md",
      "数据库热门面试题/SQL语句怎么进行的优化？.md",
      "数据库热门面试题/分布式系统下mysql事务失效怎么办？.md",
      "数据库热门面试题/大表如何进行优化.md",
      "数据库热门面试题/数据库ACID,脏读，幻读，不可重复读，四种隔离级别.md",
      "数据库热门面试题/数据库最有效的清理方式.md",
      "数据库热门面试题/水平分表的策略.md",
      "数据库热门面试题/水平垂直分库之后代码要如何修改？.md",
      "数据库热门面试题/b树和b+树的区别.md",
      "数据库热门面试题/Innodb引擎执行update语句的执行流程.md",
      "数据库热门面试题/MySQL关键字的执行顺序.md",
      "数据库热门面试题/MySQL存储引擎，MyISAM和InnoDB的特点和使用场景.md",
      "数据库热门面试题/MySQL的主从复制.md",
      "数据库热门面试题/数据库MVCC.md",
      "数据库热门面试题/数据库的两阶段提交是怎么样的？.md",
      "数据库热门面试题/聚簇索引和非聚簇索引.md",
    ],
  },
  {
    title: "操作系统热门面试题",
    collapsable: true,
    children: [
      "操作系统热门面试题/CPU指令重排序的好处.md",
      "操作系统热门面试题/为什么用户态和内核态之间的切换会影响到线程的执行效率，真正慢的点在哪里？.md",
      "操作系统热门面试题/多核CPU下，三级缓存对于每个内核来说是共享的吗？那你知道它的数据存储以及指令存储的方式有了解过吗？.md",
      "操作系统热门面试题/怎么解决死锁？.md",
      "操作系统热门面试题/操作系统有一个锁的概念，谈谈你对它的理解？.md",
      "操作系统热门面试题/查看线程状态的工具.md",
      "操作系统热门面试题/死锁产生的条件.md",
      "操作系统热门面试题/用户态和内核态的区别？.md",
      "操作系统热门面试题/线程的生命周期.md",
      "操作系统热门面试题/零拷贝技术.md",
    ],
  },
  {
    title: "Redis热门面试题",
    collapsable: true,
    children: [
      "Redis热门面试题/Redis数据类型有哪些？.md",
      "Redis热门面试题/redis的持久化.md",
      "Redis热门面试题/Redis集群模式.md",
      "Redis热门面试题/为什么要使用redis,使用redis和传统sql有哪些好处.md",
      "Redis热门面试题/怎么解决数据库缓存数据一致性问题？.md",
    ],
  },
];
