export default [
  "",
  {
    title: "Java热门面试题",
    collapsable: true,
    children: [
      "Java热门面试题/JDK和JRE有什么区别？.md",
      "Java热门面试题/Java的重要特点说几个.md",
      "Java热门面试题/==和equals的区别是什么？.md",
      "Java热门面试题/BIO、NIO、AIO有什么区别？.md",
      "Java热门面试题/final在Java中有什么引用？.md",
      "Java热门面试题/Java的基本数据类型有哪些？.md",
      "Java热门面试题/Math.round、Math.ceil、Math.floor用法.md",
      "Java热门面试题/String,StringBuffer,StringBuilder之间的区别和联系.md",
      "Java热门面试题/String两种创建对象的区别.md",
      "Java热门面试题/为什么要使用克隆 怎么实现对象克隆 克隆有几种方式和它们的区别？.md",
      "Java热门面试题/什么是反射？反射有哪些作用？反射在Spring中的体现.md",
      "Java热门面试题/常见的运行时异常有哪些？.md",
      "Java热门面试题/抽象类和普通类的区别在哪里？.md",
      "Java热门面试题/接口和抽象类有什么区别和联系？.md",
      "Java热门面试题/重写和重载的区别和使用场景.md",
    ],
  },
  {
    title: "计算机网络热门面试题",
    collapsable: true,
    children: [
      "计算机网络热门面试题/GET 请求和 POST 请求的区别.md",
      "计算机网络热门面试题/http和https的区别.md",
      "计算机网络热门面试题/OSI七层协议？.md",
      "计算机网络热门面试题/TCP三次握手和四次挥手，为什么不能是两次握手，三次挥手？.md",
      "计算机网络热门面试题/TCP和UDP传输协议的区别？.md",
      "计算机网络热门面试题/TCP和UDP的区别.md",
      "计算机网络热门面试题/TLS加密的过程.md",
      "计算机网络热门面试题/TLS的握手过程.md",
      "计算机网络热门面试题/对加密方式有了解吗？.md",
      "计算机网络热门面试题/拥塞控制、超时重传的具体原理？.md",
    ],
  },
  {
    title: "数据库热门面试题",
    collapsable: true,
    children: [
      "数据库热门面试题/MySQL回表.md",
      "数据库热门面试题/MySQL常见索引.md",
      "数据库热门面试题/MySQL的undolog,redolog,binlog.md",
      "数据库热门面试题/SQL语句怎么进行的优化？.md",
      "数据库热门面试题/分布式系统下mysql事务失效怎么办？.md",
      "数据库热门面试题/大表如何进行优化.md",
      "数据库热门面试题/数据库ACID,脏读，幻读，不可重复读，四种隔离级别.md",
      "数据库热门面试题/数据库最有效的清理方式.md",
      "数据库热门面试题/水平分表的策略.md",
      "数据库热门面试题/水平垂直分库之后代码要如何修改？.md",
    ],
  },
];
